---
title: "WDL Workflows"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Description about Course/Book."
favicon: assets/AnVIL_style/anvil_favicon.ico
output:
    bookdown::word_document2:
      toc: true
---

# Overview {-}

This book introduces WDL Workflows on AnVIL.  After introducing several concepts, including basic WDL syntax, we present hands-on exercises to run a workflow, write a WDL, localize a file, customize a Docker image, and join the Discourse.  No local software installation is required as each exercise leverages web-based resources.

```{r, echo=FALSE, warning=FALSE}
ottrpal::include_slide("https://docs.google.com/presentation/d/1o2XnuMbqWVLf4XrsXolIQ7ulfnMlpJlrUxN0Y8aLIVQ/edit#slide=id.g1397c25e58c_0_2")
```

## Skills Level {-}

::: {.notice}
_Genetics_  
**Novice**: No genetics knowledge needed

_Programming skills_  
**Novice**: No programming experience needed
:::

## Learning Objectives {-}

- Understand when WDL Workflows are the right tool
- Run a Workflow on AnVIL
- Write a WDL using Broad Methods Repository
- Bring your own data to analyze
- Customize your Docker environment
- Join the conversation

## AnVIL Collection {-}

Please check out our full collection of AnVIL and related resources: https://hutchdatascience.org/AnVIL_Collection/
